on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  build:
    name: Build and scan docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: vulnerable:latest
          load: true

      - name: check local images
        run: docker images

      - name: export as tar
        run: docker save vulnerable:latest -o vulnerable.tar

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.18.0
        with:
          input: vulnerable.tar  
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: show sarif
        run: cat trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
